version: "3.9"

services:
  backend:
    build: .
    container_name: viral_tweet_backend
    command: uvicorn src.services.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: .
    container_name: viral_tweet_frontend
    command: streamlit run streamlit/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
